"""
Scenario generation service with OpenAI GPT-4o integration.
Generates conversation scenarios from projects and schedules.
"""
import logging
from typing import List, Dict, Any, Optional
from openai import AsyncOpenAI
import httpx
import json

from app.config import settings
from app.models.scenario import Scenario
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)


class ScenarioService:
    """Service for generating and managing conversation scenarios."""

    def __init__(self):
        """Initialize OpenAI client."""
        self.client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

    async def generate_from_projects(
        self,
        project_ids: List[str],
        schedule_ids: List[str],
        document_ids: List[str],
        language: str,
        difficulty: str,
        count: int,
        user_id: str,
        jwt_token: str,
        db: Session
    ) -> List[Dict[str, Any]]:
        """
        Generate scenarios from projects and schedules using GPT-4o.

        Args:
            project_ids: List of project UUIDs
            schedule_ids: List of schedule UUIDs
            document_ids: List of document UUIDs
            language: Target language (en, ko, zh, ja)
            difficulty: Difficulty level (beginner, intermediate, advanced)
            count: Number of scenarios to generate
            user_id: User UUID
            jwt_token: JWT token for Java API calls
            db: Database session

        Returns:
            List of generated scenario dictionaries
        """
        logger.info(f"🚀 Starting scenario generation: user={user_id}, projects={len(project_ids)}, schedules={len(schedule_ids)}, documents={len(document_ids)}")

        # 1. Fetch context from Java backend
        context = await self._fetch_context(project_ids, schedule_ids, document_ids, jwt_token)
        logger.info(f"📝 Context fetched: {len(context)} characters")

        # 2. Generate scenarios with GPT-4o
        scenarios_data = await self._generate_with_gpt(context, language, difficulty, count)
        logger.info(f"🤖 GPT-4o generated {len(scenarios_data)} scenarios")

        # 3. Save to PostgreSQL
        saved_scenarios = []
        for idx, scenario_data in enumerate(scenarios_data):
            try:
                scenario = Scenario(
                    user_id=user_id,
                    title=scenario_data["title"],
                    description=scenario_data["description"],
                    scenario_text=scenario_data["scenarioText"],
                    language=language,
                    difficulty=difficulty,
                    category=scenario_data["category"],
                    roles=scenario_data["roles"],
                    required_terminology=scenario_data.get("requiredTerminology", []),
                    project_ids=project_ids,
                    schedule_ids=schedule_ids,
                    document_ids=document_ids,
                    auto_generated=True
                )
                db.add(scenario)
                db.flush()

                saved_scenarios.append({
                    "id": str(scenario.id),
                    "title": scenario.title,
                    "description": scenario.description,
                    "scenarioText": scenario.scenario_text,
                    "language": scenario.language,
                    "difficulty": scenario.difficulty,
                    "category": scenario.category,
                    "roles": scenario.roles,
                    "requiredTerminology": scenario.required_terminology,
                    "autoGenerated": scenario.auto_generated,
                    "createdAt": scenario.created_at.isoformat()
                })

                logger.info(f"💾 Saved scenario {idx + 1}/{len(scenarios_data)}: {scenario.title}")

            except Exception as e:
                logger.error(f"❌ Failed to save scenario {idx + 1}: {str(e)}")
                continue

        db.commit()
        logger.info(f"✅ Successfully saved {len(saved_scenarios)}/{len(scenarios_data)} scenarios")

        return saved_scenarios

    async def _fetch_context(
        self,
        project_ids: List[str],
        schedule_ids: List[str],
        document_ids: List[str],
        jwt_token: str
    ) -> str:
        """
        Fetch context from Java backend (projects, schedules, and documents).

        Args:
            project_ids: List of project UUIDs
            schedule_ids: List of schedule UUIDs
            document_ids: List of document UUIDs
            jwt_token: JWT token for authentication

        Returns:
            Combined context string
        """
        headers = {"Authorization": f"Bearer {jwt_token}"}
        context_parts = []

        async with httpx.AsyncClient() as client:
            # Fetch project information
            for pid in project_ids:
                try:
                    response = await client.get(
                        f"http://localhost:3000/api/projects/{pid}",
                        headers=headers,
                        timeout=10.0
                    )
                    if response.status_code == 200:
                        project = response.json()
                        context_parts.append(
                            f"Project: {project.get('name', '')}\n"
                            f"Description: {project.get('description', '')}"
                        )
                        logger.info(f"✅ Fetched project: {project.get('name', '')}")
                    else:
                        logger.warning(f"⚠️  Failed to fetch project {pid}: status {response.status_code}")
                except Exception as e:
                    logger.warning(f"⚠️  Failed to fetch project {pid}: {str(e)}")

            # Fetch schedule information
            for sid in schedule_ids:
                try:
                    response = await client.get(
                        f"http://localhost:3000/api/schedules/{sid}",
                        headers=headers,
                        timeout=10.0
                    )
                    if response.status_code == 200:
                        schedule_data = response.json()
                        schedule = schedule_data.get('data', {})
                        context_parts.append(
                            f"Schedule: {schedule.get('title', '')}\n"
                            f"Description: {schedule.get('description', '')}\n"
                            f"Location: {schedule.get('location', 'N/A')}"
                        )
                        logger.info(f"✅ Fetched schedule: {schedule.get('title', '')}")
                    else:
                        logger.warning(f"⚠️  Failed to fetch schedule {sid}: status {response.status_code}")
                except Exception as e:
                    logger.warning(f"⚠️  Failed to fetch schedule {sid}: {str(e)}")

            # Fetch document contents
            for doc_id in document_ids:
                try:
                    response = await client.get(
                        f"http://localhost:3000/api/documents/{doc_id}",
                        headers=headers,
                        timeout=10.0
                    )
                    if response.status_code == 200:
                        doc_data = response.json()
                        document = doc_data.get('data', {})

                        # Extract page contents (limit to first 5 pages, 500 chars per page)
                        contents = document.get('contents', [])[:5]
                        if contents:
                            text_parts = []
                            for content in contents:
                                page_text = content.get('content', '')[:500]
                                if page_text:
                                    text_parts.append(f"Page {content.get('pageNumber', '?')}: {page_text}")

                            if text_parts:
                                context_parts.append(
                                    f"Document: {document.get('originalFilename', '')}\n"
                                    + "\n".join(text_parts)
                                )
                                logger.info(f"✅ Fetched document: {document.get('originalFilename', '')} ({len(contents)} pages)")
                        else:
                            logger.warning(f"⚠️  Document {doc_id} has no content")
                    else:
                        logger.warning(f"⚠️  Failed to fetch document {doc_id}: status {response.status_code}")
                except Exception as e:
                    logger.warning(f"⚠️  Failed to fetch document {doc_id}: {str(e)}")

        # Fallback to general context if no data fetched
        if not context_parts:
            logger.warning("⚠️  No context fetched, using general business scenarios")
            return "General business communication scenarios for professional practice."

        return "\n\n".join(context_parts)

    async def _generate_with_gpt(
        self,
        context: str,
        language: str,
        difficulty: str,
        count: int
    ) -> List[Dict[str, Any]]:
        """
        Generate scenarios using GPT-4o.

        Args:
            context: Context from projects/schedules
            language: Target language
            difficulty: Difficulty level
            count: Number of scenarios to generate

        Returns:
            List of scenario dictionaries
        """
        # Language mapping
        lang_map = {
            "en": "English",
            "ko": "Korean (한국어)",
            "zh": "Chinese (中文)",
            "ja": "Japanese (日本語)",
            "vi": "Vietnamese (Tiếng Việt)"
        }
        target_lang = lang_map.get(language, "English")

        # Check if this is everyday scenario (no project selected)
        is_everyday_scenario = context == "General business communication scenarios for professional practice."

        if is_everyday_scenario:
            # Everyday conversation scenarios
            prompt = f"""다음은 일상생활에서 자주 접하는 {count}개의 실용적인 회화 시나리오를 생성해주세요.
이 시나리오는 {target_lang} 언어 연습을 위한 것입니다.

시나리오 타입 (다양하게 선택):
- 식당에서의 대화 (주문, 예약, 불만 처리)
- 호텔 체크인/체크아웃
- 쇼핑 (옷, 전자제품, 식료품)
- 병원/약국 방문
- 은행 업무
- 우체국/택배
- 카페에서 주문
- 교통 수단 이용 (택시, 지하철, 버스)
- 헬스장/피트니스 센터
- 미용실/헤어샵
- 부동산 문의
- 렌터카 대여

요구사항:
- 난이도: {difficulty}
- 목표 언어: {target_lang}
- 각 시나리오는 일상생활에서 실제로 겪을 수 있는 상황을 반영
- 해당 상황에서 자주 사용하는 3-5개의 실용적인 표현이나 어휘를 포함
- 다양한 일상 상황을 다루세요
- 제목과 설명은 반드시 한글로 작성
- 역할 설명은 간단하고 간결하게 (1-2 단어)

다음 JSON 형식으로 시나리오를 생성하세요:
{{
  "scenarios": [
    {{
      "title": "한글로 된 시나리오 제목 (예: 식당에서 음식 주문하기, 호텔 체크인하기)",
      "description": "한글로 된 간단한 설명 (2-3 문장). 어떤 상황인지 명확하게 설명",
      "scenarioText": "개조식으로 작성된 상세한 시나리오 설명 (한글). 각 항목을 '-'로 시작하여 줄바꿈으로 구분합니다.",
      "category": "Restaurant|Hotel|Shopping|Hospital|Bank|Post Office|Cafe|Transportation|Fitness|Beauty|Real Estate|Car Rental|Daily Life",
      "roles": {{
        "user": "{target_lang}로 된 간단한 사용자 역할 (예: Customer, Patient, Guest 등)",
        "ai": "{target_lang}로 된 간단한 상대방 역할 (예: Waiter, Receptionist, Sales Clerk 등)"
      }},
      "requiredTerminology": ["해당 상황에서 유용한 표현1", "표현2", "표현3"]
    }}
  ]
}}

중요 사항:
- title: 반드시 한글로 작성 (일상 상황 명확히 표현)
- description: 반드시 한글로 작성
- scenarioText: 반드시 개조식으로 작성 (각 항목은 '-'로 시작하고 줄바꿈으로 구분)
  예시 형식:
  "scenarioText": "- 상황: 해외 호텔에서 체크인하는 상황입니다\\n- 목표: 예약 확인, 방 배정, 시설 이용 안내를 {target_lang}로 대화합니다\\n- 연습 내용: 예약 정보 확인, 여권 제시, 결제 방법 설명\\n- 주요 표현: 'reservation confirmation', 'check-in', 'amenities'\\n- 난이도: {difficulty} 수준에 맞는 표현 사용"
- category: 일상 생활 카테고리 사용 (비즈니스 관련 카테고리 사용 금지)
- roles.user: {target_lang}로 된 간단한 역할 (예: "Customer", "Patient", "손님", "환자")
- roles.ai: {target_lang}로 된 간단한 서비스 제공자 역할 (예: "Waiter", "Doctor", "웨이터", "의사") - "AI"나 "Assistant" 사용 금지
- requiredTerminology: 해당 상황에서 실제로 사용하는 유용한 표현이나 어휘

정확히 {count}개의 일상 회화 시나리오를 "scenarios" 배열에 생성하세요."""

            system_content = f"당신은 일상생활 회화 시나리오를 만드는 전문가입니다. {target_lang} 언어 연습에 적합한 실용적이고 현실적인 일상 대화 시나리오를 생성합니다. 제목, 설명, 시나리오 텍스트는 항상 한글로 작성하고, 역할 설명은 간단하게 (1-2 단어) 작성합니다. 'ai' 역할은 '웨이터', '직원', '의사' 같은 현실적인 서비스 제공자 역할을 사용하며, 절대 'AI'나 'Assistant'를 사용하지 않습니다. 비즈니스나 업무 관련 시나리오는 생성하지 않습니다."

        else:
            # Business scenarios with project context
            prompt = f"""다음 컨텍스트를 기반으로 {count}개의 현실적인 비즈니스 회화 시나리오를 생성해주세요.
이 시나리오는 {target_lang} 언어 연습을 위한 것입니다.

컨텍스트:
{context[:3000]}

요구사항:
- 난이도: {difficulty}
- 목표 언어: {target_lang}
- 각 시나리오는 현실적인 비즈니스 상황을 반영해야 합니다
- 컨텍스트에서 3-5개의 핵심 전문 용어를 식별하세요
- 다양한 시나리오 타입 사용: Collaboration, Technical Support, Product Explanation, Problem Solving
- 제목과 설명은 반드시 한글로 작성
- 역할 설명은 간단하고 간결하게 (1-2 단어)

다음 JSON 형식으로 시나리오를 생성하세요:
{{
  "scenarios": [
    {{
      "title": "한글로 된 시나리오 제목",
      "description": "한글로 된 간단한 설명 (2-3 문장)",
      "scenarioText": "개조식으로 작성된 상세한 시나리오 설명 (한글). 각 항목을 '-'로 시작하여 줄바꿈으로 구분합니다.",
      "category": "Collaboration|Technical Support|Product Explanation|Problem Solving",
      "roles": {{
        "user": "{target_lang}로 된 간단한 사용자 역할 (1-2 단어)",
        "ai": "{target_lang}로 된 간단한 상대방 역할 (1-2 단어)"
      }},
      "requiredTerminology": ["용어1", "용어2", "용어3"]
    }}
  ]
}}

중요 사항:
- title: 반드시 한글로 작성
- description: 반드시 한글로 작성
- scenarioText: 반드시 개조식으로 작성 (각 항목은 '-'로 시작하고 줄바꿈으로 구분)
  예시 형식:
  "scenarioText": "- 상황: 프로젝트 킥오프 미팅 진행\\n- 목표: 프로젝트 일정, 역할 분담, 마일스톤 논의를 {target_lang}로 진행\\n- 연습 내용: 프로젝트 범위 설명, 일정 확인, 담당자 지정\\n- 주요 용어: 'milestone', 'deadline', 'deliverable'\\n- 난이도: {difficulty} 수준의 비즈니스 표현 사용"
- roles.user: {target_lang}로 된 간단한 역할 설명 (예: "Project Manager", "Developer", "프로젝트 매니저", "개발자")
- roles.ai: {target_lang}로 된 간단한 상대방 역할 (예: "Client", "Team Lead", "Colleague", "고객", "팀장", "동료") - "AI"나 "Assistant" 사용 금지

정확히 {count}개의 시나리오를 "scenarios" 배열에 생성하세요."""

            system_content = f"당신은 현실적인 비즈니스 회화 시나리오를 만드는 전문가입니다. {target_lang} 언어 연습에 적합한 잘 구조화된 시나리오를 생성합니다. 제목, 설명, 시나리오 텍스트는 항상 한글로 작성하고, 역할 설명은 간단하게 (1-2 단어) 작성합니다. 'ai' 역할은 '고객', '팀장', '동료' 같은 현실적인 상대방 역할을 사용하며, 절대 'AI'나 'Assistant'를 사용하지 않습니다."

        # Call GPT-4o
        scenario_type = "일상 회화" if is_everyday_scenario else "비즈니스"
        logger.info(f"🤖 Calling GPT-4o for {scenario_type} scenario generation (language={language}, difficulty={difficulty}, count={count})")

        response = await self.client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "system",
                    "content": system_content
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            response_format={"type": "json_object"},
            temperature=0.8
        )

        # Parse response
        result = json.loads(response.choices[0].message.content)
        scenarios = result.get("scenarios", [])

        if not scenarios:
            logger.error("❌ GPT-4o returned no scenarios")
            raise ValueError("Failed to generate scenarios from GPT-4o")

        logger.info(f"✅ GPT-4o returned {len(scenarios)} {scenario_type} scenarios")
        return scenarios

    async def create_manual(
        self,
        user_id: str,
        title: str,
        description: str,
        scenario_text: str,
        category: str,
        roles: Dict[str, str],
        required_terminology: List[str],
        language: str,
        difficulty: str,
        project_id: Optional[str] = None,
        schedule_id: Optional[str] = None,
        db: Session = None
    ) -> Dict[str, Any]:
        """
        Create a manual scenario.

        Args:
            user_id: User UUID
            title: Scenario title
            description: Brief description
            scenario_text: Detailed scenario text
            category: Scenario category
            roles: Role information dictionary
            required_terminology: List of required terms
            language: Target language
            difficulty: Difficulty level
            project_id: Optional project ID to associate with
            schedule_id: Optional schedule ID to associate with
            db: Database session

        Returns:
            Created scenario dictionary
        """
        logger.info(f"📝 Creating manual scenario: user={user_id}, title={title}, project={project_id}, schedule={schedule_id}")

        # Build project and schedule ID lists
        project_ids = [project_id] if project_id else []
        schedule_ids = [schedule_id] if schedule_id else []

        scenario = Scenario(
            user_id=user_id,
            title=title,
            description=description,
            scenario_text=scenario_text,
            language=language,
            difficulty=difficulty,
            category=category,
            roles=roles,
            required_terminology=required_terminology,
            project_ids=project_ids,
            schedule_ids=schedule_ids,
            auto_generated=False
        )

        db.add(scenario)
        db.commit()
        db.refresh(scenario)

        logger.info(f"✅ Manual scenario created: {scenario.id}")

        return {
            "id": str(scenario.id),
            "title": scenario.title,
            "description": scenario.description,
            "scenarioText": scenario.scenario_text,
            "language": scenario.language,
            "difficulty": scenario.difficulty,
            "category": scenario.category,
            "roles": scenario.roles,
            "requiredTerminology": scenario.required_terminology,
            "projectIds": scenario.project_ids,
            "scheduleIds": scenario.schedule_ids,
            "autoGenerated": scenario.auto_generated,
            "createdAt": scenario.created_at.isoformat()
        }

    async def modify_with_chat(
        self,
        current_scenario: Dict[str, Any],
        user_message: str,
        language: str,
        difficulty: str
    ) -> Dict[str, Any]:
        """
        채팅을 통한 시나리오 수정

        Args:
            current_scenario: 현재 시나리오 상태
            user_message: 사용자의 수정 요청 메시지
            language: 목표 언어
            difficulty: 난이도

        Returns:
            수정된 시나리오 필드와 AI 응답 메시지
        """
        logger.info(f"🤖 시나리오 수정 요청: message='{user_message[:50]}...'")

        # 언어 매핑
        lang_map = {
            "en": "English",
            "ko": "Korean (한국어)",
            "zh": "Chinese (中文)",
            "ja": "Japanese (日本語)",
            "vi": "Vietnamese (Tiếng Việt)"
        }
        target_lang = lang_map.get(language, "English")

        # 시스템 프롬프트
        system_prompt = f"""당신은 비즈니스 회화 시나리오를 수정하는 전문 AI 어시스턴트입니다.

사용자가 현재 시나리오에 대해 수정 요청을 하면, 요청사항을 분석하고 적절하게 시나리오를 수정해야 합니다.

현재 시나리오 상태:
- 제목: {current_scenario.get('title', '(없음)')}
- 설명: {current_scenario.get('description', '(없음)')}
- 시나리오 텍스트: {current_scenario.get('scenarioText', '(없음)')}
- 사용자 역할: {current_scenario.get('userRole', '(없음)')}
- AI 역할: {current_scenario.get('aiRole', '(없음)')}
- 카테고리: {current_scenario.get('category', 'General')}
- 필수 전문용어: {current_scenario.get('requiredTerminology', '(없음)')}

목표 언어: {target_lang}
난이도: {difficulty}

수정 지침:
1. 사용자의 요청을 정확하게 이해하고 해당 필드만 수정하세요
2. 요청하지 않은 필드는 그대로 유지하세요
3. 제목과 설명은 반드시 한글로 작성하세요
4. 시나리오 텍스트는 반드시 개조식으로 작성하세요 (각 항목을 '-'로 시작하고 줄바꿈으로 구분)
5. 시나리오 텍스트 예시: "- 상황: ...\\n- 목표: ...\\n- 연습 내용: ...\\n- 주요 표현/용어: ...\\n- 난이도: ..."
6. 역할은 간단하게 1-2 단어로 {target_lang}로 작성하세요
7. AI 역할은 "AI"나 "Assistant"가 아닌 현실적인 역할 (예: "Client", "고객", "팀장")을 사용하세요
8. 난이도 {difficulty}에 맞는 적절한 복잡도로 조정하세요

다음 JSON 형식으로 응답하세요:
{{
  "modifiedFields": {{
    "title": "수정된 제목 (한글, 변경 시에만)",
    "description": "수정된 설명 (한글, 변경 시에만)",
    "scenarioText": "수정된 시나리오 텍스트 (개조식, 한글, 변경 시에만)",
    "userRole": "수정된 사용자 역할 ({target_lang}, 변경 시에만)",
    "aiRole": "수정된 AI 역할 ({target_lang}, 변경 시에만)",
    "category": "수정된 카테고리 (변경 시에만)",
    "requiredTerminology": "수정된 전문용어 (변경 시에만)"
  }},
  "assistantMessage": "사용자에게 보낼 한글 응답 메시지 (어떤 부분을 수정했는지 간단히 설명)"
}}

중요:
- modifiedFields에는 실제로 변경된 필드만 포함하세요
- 변경하지 않은 필드는 포함하지 마세요
- scenarioText를 수정할 때는 반드시 개조식으로 작성하세요 (각 항목 '-'로 시작, 줄바꿈 구분)
- assistantMessage는 친근하고 간결하게 작성하세요 (1-2문장)"""

        # GPT-4o 호출
        response = await self.client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message}
            ],
            response_format={"type": "json_object"},
            temperature=0.7
        )

        # 응답 파싱
        result = json.loads(response.choices[0].message.content)
        modified_fields = result.get("modifiedFields", {})
        assistant_message = result.get("assistantMessage", "시나리오를 수정했습니다.")

        logger.info(f"✅ 시나리오 수정 완료: {len(modified_fields)} 필드 수정됨")

        return {
            "modifiedScenario": modified_fields,
            "message": assistant_message
        }

