"""
Pydantic schemas for Scenario API request/response validation.
"""
from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class RoleInfo(BaseModel):
    """Role information for user and AI in a scenario."""
    user: str = Field(..., description="User's role in the scenario")
    ai: str = Field(..., description="AI's role in the scenario")


class GenerateFromProjectsRequest(BaseModel):
    """Request schema for auto-generating scenarios from projects and schedules."""
    projectIds: List[str] = Field(..., alias="projectIds", description="List of project IDs")
    scheduleIds: List[str] = Field(default=[], alias="scheduleIds", description="List of schedule IDs")
    documentIds: List[str] = Field(default=[], alias="documentIds", description="List of document IDs")
    language: str = Field(default="en", description="Target language: en, ko, zh, ja")
    difficulty: str = Field(default="intermediate", description="Difficulty level: beginner, intermediate, advanced")
    count: int = Field(default=5, ge=1, le=10, description="Number of scenarios to generate (1-10)")

    class Config:
        populate_by_name = True


class ManualCreateRequest(BaseModel):
    """Request schema for manually creating a scenario."""
    title: str = Field(..., min_length=1, max_length=255, description="Scenario title")
    description: str = Field(..., min_length=1, description="Brief scenario description")
    scenarioText: str = Field(..., alias="scenarioText", min_length=1, description="Detailed scenario text")
    category: str = Field(..., description="Scenario category")
    roles: RoleInfo = Field(..., description="Role information")
    requiredTerminology: List[str] = Field(default=[], alias="requiredTerminology", description="Required terminology")
    language: str = Field(default="en", description="Target language: en, ko, zh, ja")
    difficulty: str = Field(default="intermediate", description="Difficulty level: beginner, intermediate, advanced")
    projectId: Optional[str] = Field(default=None, alias="projectId", description="Project ID to associate with")
    scheduleId: Optional[str] = Field(default=None, alias="scheduleId", description="Schedule ID to associate with")

    class Config:
        populate_by_name = True


class ScenarioResponse(BaseModel):
    """Response schema for scenario data."""
    id: str = Field(..., description="Scenario UUID")
    title: str = Field(..., description="Scenario title")
    description: str = Field(..., description="Brief scenario description")
    scenarioText: str = Field(..., alias="scenarioText", description="Detailed scenario text")
    language: str = Field(..., description="Target language")
    difficulty: str = Field(..., description="Difficulty level")
    category: str = Field(..., description="Scenario category")
    roles: RoleInfo = Field(..., description="Role information")
    requiredTerminology: List[str] = Field(..., alias="requiredTerminology", description="Required terminology")
    autoGenerated: bool = Field(..., alias="autoGenerated", description="Whether auto-generated")
    createdAt: datetime = Field(..., alias="createdAt", description="Creation timestamp")

    class Config:
        populate_by_name = True


class ScenarioListResponse(BaseModel):
    """Response schema for scenario list."""
    scenarios: List[ScenarioResponse]
    total: int = Field(..., description="Total number of scenarios")
